server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: sysgateway
  cloud:
    gateway:
      routes:
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
            # 忽略一个字符的长度
            - StripPrefix= 1
            # 限流配置
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"
                # 令牌桶中每次添加令牌频率
                redis-rate-limiter.replenishRate: 1
                # 令牌桶大小
                redis-rate-limiter.burstCapacity: 1

        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix= 1

        - id: changgou_order_web_route
          uri: lb://ORDER-WEB
          predicates:
            - Path=/api/wcart/**,/api/worder/**,/api/wxpay/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.223.130
    port: 6379
